name: VCL Tests

on:
  pull_request:
    paths:
      - 'etc/varnish6.vcl'
      - 'tests/varnish/**'
      - '.github/workflows/vcl-tests.yml'

jobs:
  test:
    needs: prepare-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Varnish test
        working-directory: tests/varnish
        run: make test
